version: '3.8'
services:
  php:
    image: php:8.3-fpm
    container_name: php_container
    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ../backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony

  node:
    image: node:20
    container_name: node_container
    volumes:
      - ../frontend:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
